version: '2'

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
  web:
    build: .
    command: >
        bash -c "sleep 10s
        && python3 manage.py migrate
        && python3 manage.py shell -c \"from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('admin', 'admin@example.com', 'admin')\"
        && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
